# Generated by Django 3.2.5 on 2021-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
