# Generated by Django 3.2.5 on 2021-08-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdata',
            name='time',
        ),
    ]
